### ISSUE TITLE
single file include for browser

### ISSUE THREAD

**Issue by lightsofapollo** [kewisch/ical.js#1]
I would like to have a single "vendorable" file to include in a browser environment. 
Usually this involves a simple make step that merges all files in the correct order and then optionally minify.

**Comment by kewisch** [comment]
I agree on this. I have been focusing on functionality rather than packaging until now, but the goal would be to use standard mechanisms (require.js?) to put together the code.

**Comment by kewisch** [comment]
Lets open a new issue for require.js, I think this can be closed with the pull request you did.
