### ISSUE TITLE
Event.iterator returning bad next date for monthly repeat

### ISSUE THREAD

**Issue by rahearn** [kewisch/ical.js#100]
While investigating #99 I noticed that when iterating over the recurring event in `samples/recur_instances.ics` `iterator.next()` is returning
- Oct 2, 2012 (correct)
- Nov 5, 2012 (one day too early)

It should be returning the 1st Tuesday of each month.

**Comment by kewisch** [comment]
I tested this and it seems to work for me.  I've added this to recur_iterator_test.js and it passes:

```
  testRRULE('FREQ=MONTHLY;INTERVAL=1;BYDAY=1TU', {
    dates: [
      '2012-10-02T10:00:00',
      '2012-11-06T10:00:00'
    ]
  });
```

Can you provide a testcase that fails? I'm happy to reopen this one if so.
