### ISSUE TITLE
Node Compatibility

### ISSUE THREAD

**Issue by mogarick** [kewisch/ical.js#105]
Hi,
Is this lib node.js compatible?
I tried to install it but the lib/index.js the package.json refers to is missing and I'm getting the following error when using require for the lib (I renamed the lib to mzc-icaljs locally for I have another ical module installed)

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'mzc-icaljs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

thank you in advance for your attention

**Comment by msiebuhr** [comment]
I've published a Node.js-enabled package as `ical.js-one.com`.

(It has a few minor hacks to allow access to some internals of TZ calculation, but it should be 100% backwards compatible.)

**Comment by kewisch** [comment]
I've published the current master to npmjs.org, sorry for the delay.

https://www.npmjs.org/package/ical.js

**Comment by msiebuhr** [comment]
The `package.json` says the libs entrypoint is `lib/index.js`, but that file isn't there (at least not on master).

**Comment by kewisch** [comment]
Thanks for the hint. I guess setting this to build/ical.js is correct. Is there anything else I am missing?
