### ISSUE TITLE
Validator.html only works in Firefox

### ISSUE THREAD

**Issue by sunesimonsen** [kewisch/ical.js#112]
If you run the validator from Chrome you will get an error saying that toSource is not defined. I don't know if this is just intentional, if is you should probably mention that the validator is Firefox only in the readme.

Object.prototype.toSource
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toSource

**Comment by kewisch** [comment]
Not intentional, using toSource was probably just a quick hack. It can probably replaced with JSON.stringify(). Does the validator still work at all? I haven't tested it after merging the latest patches.

**Comment by sunesimonsen** [comment]
Yes it works perfectly and is actually very helpful. I can see if I can fix it and send you a pull request.

**Comment by kewisch** [comment]
Thanks!
