### ISSUE TITLE
Last day of a month in a yearly rule occurs on a wrong day

### ISSUE THREAD

**Issue by Decathlon1578** [kewisch/ical.js#117]
This is bug 941425 on Mozilla comm-central.
With rules such as:
RRULE:FREQ=YEARLY;BYMONTHDAY=-1;BYMONTH=2
RRULE:FREQ=YEARLY;BYMONTHDAY=-1
the occurrences happen on wrong days and/or months.

**Comment by kewisch** [comment]
Fixed by #118
