### ISSUE TITLE
ICAL.helpers.isArray does not work correctly

### ISSUE THREAD

**Issue by darktrojan** [kewisch/ical.js#119]
Here's why: http://web.mit.edu/jwalden/www/isArray.html

**Comment by darktrojan** [comment]
I've fixed this by using Array.isArray on my fork, the only question is if you want it. Only IE<=8 would have problems, AFAICT.

**Comment by kewisch** [comment]
I think I borrowed the isArray code from some library. Looking at kangax's compat table it seems IE8 is "obsolete" so I think we can go ahead and use Array.isArray. If someone really needs to support IE8, they can always shim it.

**Comment by kewisch** [comment]
Fixed by #120
