### ISSUE TITLE
Time: startOfWeek and endOfWeek does not return dates

### ISSUE THREAD

**Issue by sunesimonsen** [kewisch/ical.js#125]
I was a bit surprised that `startOfWeek` and `endOfWeek` does not return a date like `endOfMonth` and `startOfYear`. Is that on purpose? If not I would happily create a pull request for it.

**Comment by kewisch** [comment]
Nope, this was an oversight, thanks for catching it! It might even solve a few issues in Lightning. When you create a pull request, can you make sure there is a test that covers this?

**Comment by sunesimonsen** [comment]
I'll definitely make a test for it. Thanks for taking in contributions, I
will be on it Monday.

Kind regards
Sune

**Comment by sunesimonsen** [comment]
I created a pull request that fixes the problem: #126
