### ISSUE TITLE
time.dayOfWeek does not take Time.DEFAULT_WEEK_START into consideration

### ISSUE THREAD

**Issue by sunesimonsen** [kewisch/ical.js#127]
I don't know if I'm missing something, or is it a bug that `dayOfWeek` normalizes to Sunday:

```
// Normalize to 1 = sunday
h = ((h + 6) % 7) + 1;
```

If it is a bug, I would happily try to fix it; otherwise you can close the issue.

**Comment by kewisch** [comment]
I likely needed this for integration with Lightning. How would you want to change it? I needed a function that returns 1 = Sunday, 2 = Monday, ..., 7 = Saturday

**Comment by sunesimonsen** [comment]
Maybe I don't know exactly what I want :-) I'm building a calendar that will be used by many nationalities and the users can set on which day a week starts. `Time.startOfWeek` uses `Time.dayOfWeek` and which means I get a wrong date when calling `Time.startOfWeek`. I can of cause monkey patch `Time.dayOfWeek` to return the correct index based on the user preference, but I only want to do that if it is not something this library is going to take into consideration. 

A solution could be to use `Time.DEFAULT_WEEK_START` as the `Time.dayOfWeek` offset, then I would be able to change the day the week starts on by setting that variable.

**Comment by sunesimonsen** [comment]
I can see that `Time.startDoyWeek` and `Time.nthWeekDay` takes a week start day that defaults to Sunday. But is the start of week offset not relevant to all methods that do calculations based on the day of week? Sorry if I'm just missing something completely.

**Comment by kewisch** [comment]
Can you post a testcase where `Time.startOfWeek` fails? No worries about missing something, I'd rather have one issue more to discuss than one bug more in the library :-)

**Comment by sunesimonsen** [comment]
Everything is fine as long as weeks start on Sunday, but I need weeks to be able to start any weekday. Let's say weeks start on Monday, then `Time.fromString('2015-02-15').startOfWeek()` would still return the date `2015-02-15`, but what I actually wanted was `2015-02-09`. That is quite hard to compensate for without monkey-patching `Time.dayOfWeek`. 

I have taken the monkey-patching route for now with the following code, which seems to work perfectly:

``` js
var origDayOfWeek = Time.prototype.dayOfWeek;
Time.prototype.dayOfWeek = function () {
    var dow = origDayOfWeek.call(this);
    return dow - Time.DEFAULT_WEEK_START + 1;
};
```

**Comment by sunesimonsen** [comment]
Maybe `Time.DEFAULT_WEEK_START` isn't the best variable to use for this hack, `Time.startWeek` would be better.

**Comment by sunesimonsen** [comment]
I just found out that my hack it interfering with some of the occurrence rules. So my hack does not work.

**Comment by sunesimonsen** [comment]
Hacking the `startOfWeek` and `endOfWeek` methods seems to work better.

``` js
ical.Time.weekStart = ical.Time.DEFAULT_WEEK_START;

ical.Time.prototype.startOfWeek = function () {
    var result = this.clone();
    result.day -= this.dayOfWeek() - ical.Time.weekStart;
    result.isDate = true;
    result.hour = 0;
    result.minute = 0;
    result.second = 0;
    return result;
};

ical.Time.prototype.endOfWeek = function () {
    var result = this.clone();
    result.day += 7 - this.dayOfWeek() - ical.Time.weekStart + ical.Time.SUNDAY;
    result.isDate = true;
    result.hour = 0;
    result.minute = 0;
    result.second = 0;
    return result;
};
```

**Comment by kewisch** [comment]
How is this? Needs an analogous version for endOfWeek of course, and a few tests.

``` javascript
startOfWeek: function startOfWeek(aWeekStart) {
  var wkst = (aWeekStart || ICAL.Time.SUNDAY)
  var result = this.clone();
  result.day -= ((this.dayOfWeek() + 7 - wkst) % 7);
  result.isDate = true;
  result.hour = 0;
  result.minute = 0;
  result.second = 0;
  return result;
}
```

**Comment by sunesimonsen** [comment]
Yes that is a good idea and would fit in nicely with the current API. I can do a pull request for it, if you want.

**Comment by kewisch** [comment]
Yes, please :) Thanks for taking care!

**Comment by sunesimonsen** [comment]
Great - will do that tomorrow or Monday. I am the one thanking you, this library saves me a huge amount of effort developing our calendar. I mush rather contribute to something open source then building everything from scratch internally.

**Comment by sunesimonsen** [comment]
I created a pull request for the change as promised: #130.
