### ISSUE TITLE
Latest ical.js fails to parse x-wr-timezone

### ISSUE THREAD

**Issue by KevinGrandon** [kewisch/ical.js#136]
I'm not exactly sure what is happening here, but when trying to upgrade ical.js we are running into a test failure. Our test component looks like this: 

```
[ [ 'prodid',
    {},
    'text',
    '-//Google Inc//Google Calendar 70.9054//EN' ],
  [ 'version', {}, 'text', '2.0' ],
  [ 'calscale', {}, 'text', 'GREGORIAN' ],
  [ 'x-wr-calname', {}, 'unknown', 'calmozilla1@gmail.com' ],
  [ 'x-wr-timezone', {}, 'unknown', 'America/Los_Angeles' ] ]
```

On which we do:

``` js
var comp = new ICAL.Component(expectedComponent);
var timezone = comp.getFirstSubcomponent('vtimezone');
```

Timezone is now null, so I'm assuming that the x-wr-timezone is failing to be parsed.

**Comment by kewisch** [comment]
In #106 I made some changes to how the parser is being called.  Maybe this is why why its failing? Last I tried to adapt Lightning to use the latest ICAL.js I did have some issues too so API for parsing might not be perfect. If that is the issue you are running into, maybe you can take a look at the new API and make some corrections?

**Comment by kewisch** [comment]
@KevinGrandon any updates on this?

**Comment by kewisch** [comment]
I suspect this isn't an issue anymore. I see now you are getting the first vtimezone subcomponent, but this is not related to the x-wr-timezone property. I don't have plans to auto-parse x-wr-timezone and provide a timezone for it, but you can use the timezone service to get the timezone for the value of x-wr-timezone
