### ISSUE TITLE
Custom Organizer

### ISSUE THREAD

**Issue by sebay00** [kewisch/ical.js#141]
Hi,

Again me ... Sorry. 
I wonder if we could set a "custom" organizer like `ORGANIZER;CN=Sebastien:mailto:user@mail.com` ?

It would be great, I could remove "Unknown Organizer" on my ICS invitation.

Seb

**Comment by TimDaub** [comment]
How did you do it?

**edit** 
```js
evt.getFirstProperty("organizer").getParameter("cn")
```
