### ISSUE TITLE
Decorating rrule is not working

### ISSUE THREAD

**Issue by fourlincoln10** [kewisch/ical.js#170]
While in the Node repl:

```
> var ICALJS = require("ical.js");
    undefined
> var icalRecur = ICAL.design.value['recur'].decorate({ freq: "WEEKLY", count: 2 });
    TypeError: undefined is not a function
    at Function.ICAL.Recur.fromString (/path/to/node_modules/ical.js/build/ical.js:4431:25)
    at Object.decorate (/path/to/node_modules/ical.js/build/ical.js:683:29)
```

As a temporary workaround, this change works:

```
decorate: function decorate(aValue) {
    // return ICAL.Recur.fromString(aValue);
    return typeof aValue == "string" ? ICAL.Recur.fromString(aValue) : new ICAL.Recur(aValue);
},
```

**Comment by kewisch** [comment]
What version are you using? On the update to 1.0 I've changed the design values api for vCard support, see 4dde47bee73cefba6fa32ebfc6dfde429bd0c0a0.

**Comment by kewisch** [comment]
`ICAL.design.icalendar.value['recur'].decorate({ freq: "WEEKLY", count: 2 });` should work with the new API. I can't seem to find code that suggests that `decorate` takes a string value though?

The recommended way to create a recur value from data is indeed `new ICAL.Recur({ freq: 'WEEKLY', count: 2 });`

**Comment by fourlincoln10** [comment]
My apologies...I was in fact using an old version of ical.js. This issue does not exist in the current version.
