### ISSUE TITLE
Feature: Helper function to clean up unreferenced timezones from icalendar object

### ISSUE THREAD

**Issue by untitaker** [kewisch/ical.js#188]
When adding/removing DUE dates from Todo objects, timezone definitions can become obsolete. It'd be nice if there were helper functions available to manage those timezones (like the one described in the title).

**Comment by kewisch** [comment]
Indeed, some code for timezone management would be nice. We have something like that in Lightning (where ical.js is also used) which is managed separately from ical.js. It would be great if we could hook into the code in a way that timezone management is not mandatory and does not complicate the code too much, while still providing the option to automatically add/remove vtimezones.

Note also, including VTIMEZONEs will no longer be mandatory in the future, see https://tools.ietf.org/html/draft-ietf-tzdist-caldav-timezone-ref-04

**Comment by untitaker** [comment]
I'd like to see a function called `fixTimezones` that removes unused timezones and adds undefined ones completely automatically. I guess it should be somehow more configurable to adapt for that RFC, but my usecase has nothing to do with CalDAV.

**Comment by wrexroad** [comment]
@kewisch should this issue be closed now that #270 has been merged?

**Comment by untitaker** [comment]
Yes indeed. Thanks!
