### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by untitaker** [kewisch/ical.js#190]
The repository doesn't include any kind of license text, the only indication that this is under the MPL can be found in the sourcefiles themselves.

**Comment by kewisch** [comment]
Yes, MPL is correct. It is mentioned in CONTRIBUTING.md. Do you think I should add a LICENSE.md? Personally I don't think it is needed at yet another location since it is mentioned both in the source files and a toplevel file.

**Comment by untitaker** [comment]
I've been told it is safer from a legal perspective. If you really don't want to copy the license text a note in the README would be apprechiated.

**Comment by kewisch** [comment]
Ok, I've added it to the README. Thanks for creating the issue!
