### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by toutpt** [kewisch/ical.js#194]
Just discover the lib, I want to read more about it and ...

http://mozilla-comm.github.io/ical.js/

->

Load denied by X-Frame-Options: http://documentup.com/mozilla-comm/ical.js/ does not permit cross-origin framing. <inconnu>

I guess there is a problem with the github pages.

**Comment by kewisch** [comment]
Yes, I need to fix this. I haven't done so because the site is really not more than the readme you can see in the github repository and I had other things on my radar.

**Comment by kewisch** [comment]
Fixed this in 0bdfb231438ac9da546b185878d31186aabc361b
