### ISSUE TITLE
Expose Olson Timezones through ICAL.TimezoneService

### ISSUE THREAD

**Issue by surajwy** [kewisch/ical.js#195]
Hi,

I checked the Grunt task file (tasks/timezone.js) where we are downloading Oslon DB and converting it to ics via vzic. But, i haven't seen any code which is using it. What i expected was that TimezoneService class will use it. 

So, my question is, in case of ICS generation, why we are not using the Oslon DB to pre fill VTIMEZONE part of an ics based on the tzid (which is required in case of recurring events).

Please correct me if i am wrong anywhere.

**Comment by kewisch** [comment]
I guess this would make sense for most web-based applications, but as the olson database will also add size to the build and there are also applications providing their own database I believe it makes sense to keep it separate. In addition, updating the olson database requires manual work on each release and therefore the copy here might be out of date often.

I can put this up as an enhancement request to provide a timezones database. In the meanwhile, you can intialize the database from http://dxr.mozilla.org/comm-central/source/calendar/timezones/zones.json

**Comment by mifi** [comment]
I made a simple wrapper for ical.js that includes the tz database, and also handles rrules, exdates and exceptions:

https://github.com/mifi/ical-expander

**Comment by kewisch** [comment]
I've (almost?) fixed this in #497. What I don't have is a way to auto-release when there is a new timezone database version. I may be able to hack together some sort of cron job with github actions, but I'm not sure when I'll get around to that.
