### ISSUE TITLE
RRULE with UNTIL parsed incorrectly when date has - and :

### ISSUE THREAD

**Issue by darktrojan** [kewisch/ical.js#197]
I'm not sure which format is supposed to be used, but putting this

```
BEGIN:VCALENDAR
RRULE:UNTIL=20151231T060000Z
RRULE:UNTIL=2015-12-31T06:00:00Z
END:VCALENDAR
```

into the validator gives `2015-12-31T06:00:00Z` for the first and `2015--1-2-T1T:06::0` for the second. This is breaking recurrences for me in Lightning.

**Comment by kewisch** [comment]
In iCalendar, it should be `RRULE:otherstuff;UNTIL=20151231T060000Z`, in jCal it should be `["rrule", {}, "recur", { ..., "until": "2015-12-31T06:00:00Z"}]`. I think the validator may need some general fixes, there is another issue open for that. Can you pinpoint this without the validator?

**Comment by darktrojan** [comment]
Yes, I was just using the validator to see what an up-to-date version did. I suppose the real problem is with whatever's writing non-spec values (Lightning/ical.js, in this case), but parsing should be able to tolerate that.

**Comment by darktrojan** [comment]
I've corrected the tests to use the right format, and made the parser able to handle both formats, which will be needed since we've stored incorrect stuff in users' databases.

**Comment by darktrojan** [comment]
I can't remember why this is still here. There may have been a reason. In any case, _bump!_

**Comment by kewisch** [comment]
Sorry for delaying this. I haven't looked into this in a while, but from memory I wasn't too happy about having the parser be more lenient with this specific case. I'd prefer more major changes that would allow the parser to be either strict, most tolerant, and maybe something in between.
