### ISSUE TITLE
Property parameters are misparsed when containing a second = sign

### ISSUE THREAD

**Issue by zoehneto** [kewisch/ical.js#201]
When I try to import the following .ics file: https://www.google.com/calendar/ical/asta.dhbw.de_c0g35t6hrh16kr4ankrqg2rdm4%40group.calendar.google.com/public/basic.ics parsing always breaks. One issue seems to be, that X-APPLE-STRUCTURED-LOCATION is not handled correctly, the other issue are '\n' linebreaks in the DESCRIPTION field. I created a jsfiddle with the latest ical data under https://jsfiddle.net/hupncr2y/ .

**Comment by zoehneto** [comment]
The issue when parsing X-APPLE-STRUCTURED-LOCATION seems to be caused by the X-APPLE-MAPKIT-HANDLE parameter which contains a base64 encoded string. Because of the trailing '=' sign at the end the _parseParameters(line, start, designSet) function breaks as it uses '=' as the parameter delimiter.

**Comment by zoehneto** [comment]
Linebreaks in the DESCRIPTION field are only an issue when they are in the middle of the text, linebreaks at the and of the description do not cause parse errors.

**Comment by zoehneto** [comment]
I've created a separate jsfiddle for the newline issue at https://jsfiddle.net/y4g6txe5/ which contains only the minimal amount of data. The issue actually doesn't occur when testing using node (probably because of different newlines). 
To work around this issue one can change the `parser._eachLine`method to use the ICAL.newLineChar `pos = buffer.indexOf(ICAL.newLineChar, lastPos) + ICAL.newLineChar.length;` instead of the current code which always assumes '\n'. This on the other hand breaks the tests on node but that might be because the ICAL.newLineChar property needs to be dynamically set for the current platform.

**Comment by kewisch** [comment]
Hi sorry I haven't gotten around to answering yet. Thank you very much for investigating. I believe @make-my-day made some changes to this recently. Is this an issue with the master branch or the latest release?

**Comment by zoehneto** [comment]
I tried it with both the master branch and the latest release, neither worked for me.

**Comment by kewisch** [comment]
The fiddle at https://jsfiddle.net/y4g6txe5/ uses \n for the newline, so the string will look like this:

```
BEGIN:VEVENT
DESCRIPTION:
A
END:VEVENT 
```

Which is indeed incorrect ics. If you add a backslash, then all is well. The first fiddle with the base64 encoding is indeed causing trouble. Can you create a reduced testcase for this? If you have suggestions on how it can be fixed in the parser, I'm also open for that :)

**Comment by zoehneto** [comment]
I created a reduced fiddle for the base64 case at https://jsfiddle.net/z0c3mLrb/. 

The issue with the \n is that it is returned like that from the server, either because somebody put them there manually or, more likely, Google Calendar or whatever app was used to create the entry in Google Calendar use \n to create newlines within the description text.

**Comment by kewisch** [comment]
If the server returns the newline that is fine, but the issue in the fiddle is a js problem with the way you construct the string. Check out this one: https://jsfiddle.net/y4g6txe5/1/

**Comment by zoehneto** [comment]
Oh, my bad, I copied the content straight from the ics file and forgot to escape the backslashes.

**Comment by zoehneto** [comment]
I've got a fix for this issue which passes all the unit and acceptance tests on my machine. You simply have to update the pos variable in parser._parseParameters so it starts searching at the end of the last value (makes more sense from a performance perspective anyway). Do you want me to submit a PR for it?

**Comment by kewisch** [comment]
Sure, go ahead! I'm happy to take a look :)
