### ISSUE TITLE
Deleted non hydrated property make _properties unaligned with jCal

### ISSUE THREAD

**Issue by strokyl** [kewisch/ical.js#214]
Hello,
Deleting a non hydrated property break the vevent.
Here a fiddle that clearly show the issue
http://jsfiddle.net/puge6naa/.

I find where the bug is from, I am going to do a PR.

**Comment by strokyl** [comment]
I find where the bug is from, I am going to do a PR.

**Comment by kewisch** [comment]
fixed by #215
