### ISSUE TITLE
Creating multiValue properties throws an error on `toICALString` call

### ISSUE THREAD

**Issue by jylauril** [kewisch/ical.js#230]
I'm having trouble creating a VEVENT component with an ical standard `CATEGORIES` property which is a multiValue field.

Per RFC(https://www.ietf.org/rfc/rfc2445.txt) `4.8.1.2 Categories`, you should be able to construct something similar to: `CATEGORIES:VALUE1,VALUE2,VALUE3`

So I tried using it like:
`prop = new ICAL.Property(["categories", {}, "text", ["VALUE1", "VALUE2", "VALUE3"]])`
Which creates the property just fine and `prop.isMultiValue` is `true`. However, when I try to call: `prop.toICALString()`, I get the following error:

```
TypeError: Object VALUE1,VALUE2,VALUE3 has no method 'replace'
  at Object.result.toICAL (./node_modules/ical.js/build/ical.js:352:23)
  at Function.ICAL.stringify.stringify.value (./node_modules/ical.js/build/ical.js:1583:36)
  at Function.ICAL.stringify.stringify.multiValue (./node_modules/ical.js/build/ical.js:1560:29)
  at Function.ICAL.stringify.stringify.property (./node_modules/ical.js/build/ical.js:1497:25)
  at Object.ICAL.Property.Property.toICALString (./node_modules/ical.js/build/ical.js:3046:29)
```

Pointing to this line: https://github.com/mozilla-comm/ical.js/blob/master/build/ical.js#L352
And it does look like it's only considering the value always to be a string.

I tried using the plain value of `"VALUE1,VALUE2,VALUE3"` instead of an array, but then it escaped all the comma characters, which is not correct.

Any thoughts on how I should proceed and if this is a bug or me just using it wrong?

**Comment by kewisch** [comment]
This does sound like a bug, I'd expect the respective `toICAL` function you linked to be called for each property value instead of just the first if the property value is an array. Do you have time to work on a fix for this? This may be a regression from one of the recent patches to the multivalue parser. cc @make-my-day

**Comment by jylauril** [comment]
Workaround for this is to do:

``` js
prop = new ICAL.Property('categories');
prop.setValues(["VALUE1", "VALUE2", "VALUE3"]);
prop.toICALString(); // -> CATEGORIES:VALUE1,VALUE2,VALUE3
```

I noticed that by doing it this way, the jCal that gets generated from that becomes:
`["categories", {}, "text", "VALUE1", "VALUE2", "VALUE3"]`
instead of:
`["categories", {}, "text", ["VALUE1", "VALUE2", "VALUE3"]]`
so I tested doing it that way:
`prop = new ICAL.Property(["categories", {}, "text", "VALUE1", "VALUE2", "VALUE3"])`
and that produced the same result: `CATEGORIES:VALUE1,VALUE2,VALUE3`

So it looks like it is actually working as intended by the RFC: https://tools.ietf.org/html/rfc7265#page-7
I personally don't like that the value has to be globbered into the same array as the property descriptor, but can't really argue against the RFC. /shrugs

I'm gonna close this issue as it seems to be working as expected, I'll just adjust my code to deal with it.

**Comment by kewisch** [comment]
Ah yes, sorry I missed that! As I've written that rfc I can actually comment on that :-) The reason we went for having the values separate is that for jCard, which is very similar to jCal, there are also structured values. For this we use the array in a single value. See https://tools.ietf.org/html/rfc7095#section-3.3.1.3 for details.

**Comment by jylauril** [comment]
Yeah, I guessed there was a reason for that. :)
Thanks for the explanation and looking into this!
