### ISSUE TITLE
ICAL.Recur.fromString and .toString not iCal/RFC5545 compatible

### ISSUE THREAD

**Issue by stevesims** [kewisch/ical.js#243]
According to RFC5545, `UNTIL` values are `DATE` or `DATE-TIME` strings, which do not contain hyphens or colons.  The values produced by ical.js however do contain them.

`fromString` crashes when passed a standard-compliant `RRULE` string that includes an `UNTIL` value.

A work-around to this is to use `ICAL.Recur.fromData(ICAL.Recur._stringToData(rrule, true))`, which will parse the `UNTIL` value correctly.

Using `toString` on objects that include an until date generates a rule string that doesn't comply with the RFC5545 spec.  There's no simple work-around to this issue.

Not complying to the spec is problematic, as it prevents interoperability with other systems/libraries.

It appears that #198 may resolve this issue.

**Comment by kewisch** [comment]
`fromString` actually take a RFC7265 compliant string, with hyphens and colons. If you want to convert from iCalendar, you can use the design data to translate the string. Check out https://github.com/mozilla-comm/ical.js/wiki/Parser-Design-Data#conversion-between-icalendar-and-jcal-values
