### ISSUE TITLE
Finding all events between a time period

### ISSUE THREAD

**Issue by belaviyo** [kewisch/ical.js#252]
Considering using `ICAL.parse` to parse a iCal source, is there anyway to find all the events occurring on the next 12 hours

**Comment by midzer** [comment]
Hi,
i use ical.js to find events for a specific day.
Maybe my implementation is helpful for you https://github.com/midzer/eisolzried/blob/master/js/main.js

**Comment by kewisch** [comment]
The standard way to do this is to get an iterator, fast forward to the start of the period, then iterate until the end of the period has come. I have some preliminary work to make this faster at https://github.com/kewisch/ical.js/tree/recparserv2 but this is not ready for production yet.
