### ISSUE TITLE
Yearly recurring events broken

### ISSUE THREAD

**Issue by midzer** [kewisch/ical.js#261]
With .ics data from http://www.ifeiertage.de/ i have issues with events that recurr yearly.

```
var expand = event.iterator(time);
var next = expand.next();
```

While debugging i discovered, that next() returns same date as initial `time`. So it does not return the next occurence of new years eve for example.

You can find my whole implementation here https://github.com/midzer/eisolzried/blob/master/js/main.js#L7

**Comment by kewisch** [comment]
This is expected and matches what libical does. Since the first occurrence of the event is actually the one at the initial time, it is correct. The first instance could also be an exception or otherwise excluded, in which case this would not be the case.
