### ISSUE TITLE
Where are the tutorials/guides?

### ISSUE THREAD

**Issue by ajaska** [kewisch/ical.js#264]
Hey, the docs are filled with references to "layers" and "terminology" guides, but there don't seem to be any corresponding tutorials generated by `grunt jsdoc`, and I can't seem to find the corresponding html/md tutorial files on the project. They're not on the generated API/wiki either.

Am I looking in the wrong place? Were those lost somewhere?

**Comment by kewisch** [comment]
Did you mean this link? http://mozilla-comm.github.io/ical.js/api/

**Comment by ajaska** [comment]
Yes, see http://mozilla-comm.github.io/ical.js/api/ICAL.Event.html for example.

"See the layers guide for more details." -> This is unlinked. 

```
   * @classdesc                                                                    
   * ICAL.js is organized into multiple layers. The bottom layer is a raw jCal  
   * object, followed by the component/property layer. The highest level is the 
   * event representation, which this class is part of. See the                    
   * {@tutorial layers} guide for more details.
```

The `layers` tutorial does not seem to exist. This is also the case for the `terminology` tutorial. Just grep (or ag 😄) the source directory for for `tutorial` to find these jsdoc references.

**Comment by kewisch** [comment]
Ah yes, I never wrote those. There is some information on the layers at https://github.com/mozilla-comm/ical.js/wiki#component-model-layer. The three layers are event (using `ICAL.Event`), component access (using `ICAL.Component`), or the raw access to the jCal object.

**Comment by ajaska** [comment]
Haha, welp, thanks anyway.
