### ISSUE TITLE
ICAL.Recur constructor/fromData does not take a freq argument

### ISSUE THREAD

**Issue by ajaska** [kewisch/ical.js#271]
The documentation: http://mozilla-comm.github.io/ical.js/api/ICAL.Recur.html

> Constructor
> new Recur(data, freq)

Disagrees with the actual code:
https://github.com/mozilla-comm/ical.js/blob/892e969cc0e7d814aa3d0d10c0411b73a08be770/lib/ical/recur.js#L54-L61

`ICAL.Recur = function icalrecur(data) {`

(`ICAL.Recur.fromData` as well).

**Comment by kewisch** [comment]
Thanks for the note! This looks like a copy/paste error and just needs to be fixed in the jsdoc. Do you think you could prepare a pull requests for this? I would appreciate!
