### ISSUE TITLE
Unable to define custom event properties

### ISSUE THREAD

**Issue by jkndrkn** [kewisch/ical.js#272]
I want to create custom event properties.

This documentation implies that this can be done using ICAL.design.registerProperty: https://github.com/mozilla-comm/ical.js/wiki/Parser-Design-Data

However, the method ICAL.design.registerProperty does not exist.

How does one create custom event properties?

**Comment by jkndrkn** [comment]
Commit 4dde47bee73cefba6fa32ebfc6dfde429bd0c0a0 removed registerProperty. Maybe it could be re-added?

**Comment by jkndrkn** [comment]
On closer inspection, using http://mozilla-comm.github.io/ical.js/api/ICAL.Component.html#addPropertyWithValue is all that is needed to add a custom property. The wiki should be updated to reflect this.

**Comment by jkndrkn** [comment]
Reopened to signal that Wiki needs revision.

**Comment by georgehrke** [comment]
The wiki is open for editing to everyone. I guess @kewisch would appreciate a contribution from your side here ;)

**Comment by kewisch** [comment]
Taken care of, https://github.com/mozilla-comm/ical.js/wiki/Parser-Design-Data/_compare/de2040b102c7364043d549bcdbb86545f0d69d61...30f9080be056a343cba93e8fdbb16fcda11363e2
