### ISSUE TITLE
Clear/Reset events ?

### ISSUE THREAD

**Issue by yabdab** [kewisch/ical.js#286]
I am parsing several ics feeds and need to be able to clear out all previous events prior to starting the next. Is there a way to this? Currently all the events are duplicated and I do not want that.

**Comment by georgehrke** [comment]
I'm not sure I understood your issue 100%, but [`removeAllSubcomponents('vevent')`](http://mozilla-comm.github.io/ical.js/api/ICAL.Component.html#removeAllSubcomponents) should solve your issue.

Some example code would be useful :)

**Comment by kewisch** [comment]
Thanks for the comment @georgehrke ! I'm closing this issue for now, please reopen if it is still a problem.
