### ISSUE TITLE
toICALString adds backslashes before commas

### ISSUE THREAD

**Issue by MichaelBailly** [kewisch/ical.js#287]
Hello mozillians, Phillip,

We are in the process of upgrading ical.js from 1.0.2 to 1.1.2. I encountered a change in the way toICALString works : it adds a backslash before commas. Quick example:

```javascript
const ICAL = require('./build/ical.js');

const vcard = new ICAL.Component('vcard');
vcard.addPropertyWithValue('photo', '1,2');
const photo = vcard.getFirstProperty('photo');

console.log(photo.toICALString());
// PHOTO:1\,2
```

Is that the expected result from toICALString ?

**Comment by kewisch** [comment]
This looks like a bug to me. `PHOTO` is an `uri` type by default, the design set for vcard4 assumes this is a standard text type here: https://github.com/mozilla-comm/ical.js/blob/master/lib/ical/design.js#L573. Text types make use backslash escaping.

If you need a workaround for now, you can add `photo.type = "unknown";`. We might be able to just remove the uri type from values, or better yet add a passthrough. Including @amrod- who last did some refactorings and changes in that area. Do you have a good suggestion?

**Comment by amrod-** [comment]
For vcard4 this is correct behaviour:
The value type of PHOTO is URI see rfc6350 section-6.2.4
All comma characters in a value must be escaped with an backslash see rfc6350 section-3.4

**Comment by kewisch** [comment]
Ah yes, thanks for pointing to that section! I was just looking at section 4.2 and didn't find anything. I'm going to close this, @MichaelBailly let me know if you have questions!

**Comment by MichaelBailly** [comment]
ofc, thank you both of you for this explanation
