### ISSUE TITLE
Recursion error when parsing a VTIMEZONE in an English ICS, works fine in the same one in French

### ISSUE THREAD

**Issue by ddolcimascolo** [kewisch/ical.js#292]
Hi @kewisch,

I hope you're doing well :)
We're still using ical.js in OpenPaas are it gives nice results. I do came on an issue that I couldn't explain, even after trying to understand relevant part of the code.

I have two ICS I receive from Outlook.com (https://outlook.live.com/owa/?path=/calendar/view/WorkWeek). One in english [INBOX-454-en.ics.txt](https://github.com/mozilla-comm/ical.js/files/804174/INBOX-454-en.ics.txt) and one in french [INBOX-454-fr.ics.txt](https://github.com/mozilla-comm/ical.js/files/804173/INBOX-454-fr.ics.txt). You'll notice that the only differences are in the TZID of the timezone and obviously in the DTSTART and DTEND properties that references the Timezone.

Parsing the french one and accessing individual properties works fine.
Parsing the english one triggers the below error

```
Error: Same occurrence found twice, protecting you from death by recursion
    at icalrecur_iterator_next [as next] (ical.js:5245)
    at icaltimezone._expandComponent (ical.js:3335)
    at icaltimezone._ensureCoverage (ical.js:3237)
    at icaltimezone.utcOffset (ical.js:3123)
    at icaltime.utc_offset [as utcOffset] (ical.js:4017)
    at icaltime.toUnixTime (ical.js:4185)
    at icaltime.toJSDate (ical.js:4063)
    at _calMoment (fc-moment.js:25)
    at CalendarShell.get end [as end] (calendar-shell.js:159)
    at eval (eval at zf (angular.js:12683), <anonymous>:8:4)
```

Do you have an idea what causes this?

Thanks a lot for your support,
Regards,

David

**Comment by kewisch** [comment]
Hi David,

the en version is using 20170227T16300 while the fr version is using 20170228T1700 and there is a similar difference with the end dates. While there is only a minor offset in the dates and times, this might be the cause (but not the error).

The error message comes when there are two same occurrences from the recurrence iterator, which should normally not happen. The stack shows that it seems to be happening while expanding the timezone coverage, so it is using the RRULE from the VTIMEZONE and running into issues there.

I can imagine there may be some strange interaction with how the start date of the event determines the amount of coverage to expand. Can you try with a few different DTSTART/DTENDs to see if changing them makes the issue disappear?

We'll have to do some debugging in the recurrence iterator to find out where exactly the issue occurs.
