### ISSUE TITLE
Enable running tests on xpcshell

### ISSUE THREAD

**Issue by lightsofapollo** [kewisch/ical.js#3]
I have a lot of my own tooling to do this these days from marionette js client (which has tests that run on chrome, firefox, xpcshell, nodejs).

I think we need to discuss this first.

@kewisch

**Comment by kewisch** [comment]
Yes, the tests should be a bit more cross-tooling compatible. Right now they were designed for xpcshell testing, but something more dynamic would be a big win.

**Comment by kewisch** [comment]
I think we can close this one. As long as the ical.js code is covered with its own tests, we are good. Further integration tests can be done where its used, i.e b2g or Lightning.
