### ISSUE TITLE
Ical.js under CommonJS (Node.js) leaks global ICAL variable

### ISSUE THREAD

**Issue by moll** [kewisch/ical.js#329]
Hey,

Noticed some of my tests failing because they spot a global variable leakage. Turns out https://github.com/mozilla-comm/ical.js/blob/f3b8c7dc24a66424feb1735fe7ff38191e46ab99/lib/ical/helpers.js#L11 sets a global `ICAL` that is entirely unnecessary when running under CommonJS modules like when ran under Node.js. That `ICAL` variable should be scoped somehow to not set undesired globals. ;)

Cheers

**Comment by kewisch** [comment]
The way globals are set bothered me too in the past, but changing it was quite some effort and is likely not backwards compatible. It looks like Martin is giving it another stab though!

**Comment by pscs** [comment]
Is there any update on this? I've had problems using ical.js in Vue.JS in production mode because of the module loader (uncaught reference error). I've worked around the problem by changing line 11 to "var ICAL = module.exports; ", but that's obviously not nice for several reasons.

**Comment by mediaessenz** [comment]
I have exacly the same problem in conjuction with fullcalender.io's icalendar plugin, which uses this lib as well.
It took me hours to find the reason and using the same workaround than @pscs now, which i find quite ugly as well.

To help other people who have the same problem, here is the exact error, i got in the js console:
"Uncaught ReferenceError: assignment to undeclared variable ICAL"

To fix it, i changed line 11 of `node_modules/ical.js/build/ical.js` from 
```
ICAL = module.exports;
```
to
```
var ICAL = module.exports;
```

**Comment by raimund-schluessler** [comment]
We ran into this issue as well when trying to use `ical.js` twice on the same page. We use `ical.js` for a Tasks and Calendar widget in Nextcloud and when both are enabled, `ical.js` breaks and doesn't parse correctly anymore, see https://github.com/nextcloud/tasks/pull/1641#issuecomment-865690993. Adding `var ICAL = ...` fixes the issue for us.

Is there any possibility to get a fix for this problem into `ical.js`? Otherwise, we will have to use a fork with a hot fix for it, until it is resolved here, I guess.

**Comment by rocifier** [comment]
I'm also not able to use ical from @fullcalendar because of something related to this, it's a runtime error for me:

```
ical.js:11 Uncaught ReferenceError: ICAL is not defined
    at Object.UeCU (ical.js:11)
    at __webpack_require__ (bootstrap:84)
    at Module.e1AK (main.js:1)
    at __webpack_require__ (bootstrap:84)
    at Module.vzto (timetables.module.ts:2)
    at __webpack_require__ (bootstrap:84)
    at Module.Cxms (person-details.module.ts:2)
    at __webpack_require__ (bootstrap:84)
    at Module.ZAI4 (app.module.ts:1)
    at __webpack_require__ (bootstrap:84)
```

**Comment by kewisch** [comment]
#470 should fix most of this, the rest via es6 modules which is work in progress

**Comment by xeruf** [comment]
manually downloading and importing the latest timezones build, I got this error:
```sh
    ReferenceError: ICAL is not defined

       9 | if (typeof module === 'object') {
      10 |   // CommonJS, where exports may be different each time.
    > 11 |   ICAL = module.exports;
         |       ^
      12 | } else if (typeof ICAL !== 'object') {/* istanbul ignore next */
      13 |   /** @ignore */
      14 |   this.ICAL = {};

      at Object.<anonymous> (src/lib/ical.js:11:7)
      at Object.require (src/lib/ical.timezones.js:1:14)
      at Object.require (test/calendarUtil.test.js:1:1)
```
had to apply https://github.com/kewisch/ical.js/issues/329#issuecomment-845458107 to fix it

**Comment by xeruf** [comment]
still not working properly using ical.timzeones.js...
