### ISSUE TITLE
[Question] How could i change the timezone in iterator?

### ISSUE THREAD

**Issue by wingleungchoi** [kewisch/ical.js#338]
```
const start = ICAL.Time.fromString('2013-05-22T22:00:09Z')
const ruleString = 'FREQ=WEEKLY;BYDAY=MO;UNTIL=20141029T150006Z'
const recur = ICAL.Recur.fromData(ICAL.Recur._stringToData(ruleString'), true))
const iterator = recur.iterator(start)
```
iterator.next is finding Monday in UTC timezone.
How could i change the timezone in `iterator`?

**Comment by kewisch** [comment]
I'm suspecting you've found a solution or have moved on, but for the record, given your dtstart and the until is in UTC, the iterator is also in UTC. You can convert the result to any other timezone as needed.
