### ISSUE TITLE
Missing TZID in RECURRENCE-ID

### ISSUE THREAD

**Issue by roychoo** [kewisch/ical.js#342]
Hi,

i tried ```updatePropertyWithValue('recurrence-id', <ICAL.TIME>)``` but realised that it is always missing the timezone property,

instead of ```RECURRENCE-ID;TZID=Asia/Singapore:20171013T113000```
it will show ```RECURRENCE-ID;VALUE=DATE-TIME:20171013T113000```

any ideas?

**Comment by midzer** [comment]
Hi @roychoo 
without any testing and based on your info this looks like a potential bug to me.
`ICAL.TIME` can have a `TimeZone` optionally and it should be passed to any `Propery`, too.

I might have a look into this issue at the weekend if i have some free time.

**Comment by kewisch** [comment]
The `updatePropertyWithValue` is a fairly low level function which doesn't have a lot of knowledge of how properties are designed. While `RECURRENCE-ID` is one of those properties that can accept a TZID parameter, this might not be clear for the `X-STRANGE-THING` property. Maybe it accepts a date-time value, but is not specified to have a `TZID` parameter.

For a workaround you can of course always set the `TZID` parameter manually (make sure to exempt if it is UTC or local time).

I'm not opposed to fixing this in the code though, as long as it is done in a very general way (e.g. no special case if block), by reading information from the design data. Without having looked into how pretty this can be integrated into the code, it may be that this should be done a level higher in e.g. `ICAL.Event`.

**Comment by roychoo** [comment]
@kewisch hmm I maybe wrong but if I think i did try updateProperty dtstart with ICAL.Time property, I think the TZID is set automatically.

**Comment by marcoancona** [comment]
I encountered the same issue, not only using `updatePropertyWithValue` but also using the `ICAL.Event` `recurrenceId` setter. However the fix might be easy. Since recurrent-id has the same type of dtstart, the setter should also be the same. So it would sufficient to use

```js
set recurrenceId(value) {
      this._setTime('recurrence-id', value);
}
```
instead of
```js
set recurrenceId(value) {
      this._setProp('recurrence-id', value);
}
```
Do you see any issue with this change?

**Comment by kewisch** [comment]
Let me know if anything is left to do after the PR is merged for this issue, sounds like we might be good here?
