### ISSUE TITLE
vCard: Parse multiple types

### ISSUE THREAD

**Issue by Henni** [kewisch/ical.js#343]
> These type parameter values can be specified as a parameter list (e.g., TYPE=text;TYPE=voice) or as a value list (e.g., TYPE="text,voice").

https://tools.ietf.org/html/rfc6350#section-6.4.1

### Expected behaviour
```
TEL;VALUE=uri;TYPE=work;TYPE=voice:tel:+33-89-01-23-45
```
should be parsed to:
```json
[ "tel", { "type": ["work", "voice"] }, "uri", "tel:+33-89-01-23-45" ],
```
### Actual behaviour
The param value is set to the last occurring value:
```json
[ "tel", { "type": "voice" }, "uri", "tel:+33-89-01-23-45" ],
```

-------

I modified a vcard parser test to display the issue:
https://github.com/Henni/ical.js/commit/6d4365e374a12a20d4433f6f6a4186baafa126c3

**Comment by skjnldsv** [comment]
@mschroeder @kewisch any news from this one? This quite an important part of the rfc :)
Is it a difficult fix?

**Comment by torrentkino** [comment]
Is there progress already?

**Comment by Aa88s** [comment]
(Type=text;Type=voice)

**Comment by skjnldsv** [comment]
@torrentkino yes a pr is here https://github.com/mozilla-comm/ical.js/pull/388
