### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by marcoancona** [kewisch/ical.js#351]
The last release (1.2.2) was published on Jul 20, 2016 and now is 103 commits behind master. Is there a plan with a new release with the latest fixes?

**Comment by kewisch** [comment]
Definitely makes sense. Didn't realize it was so far behind. I'll try to get to this soon.

**Comment by bjoernricks** [comment]
Would be nice to get a new release. I need to be able to set a duration on an event which isn't supported in 1.2.2 yet.

**Comment by kokarn** [comment]
Also looking for a new version. Any progress on this or anything I can do to help speed that process up?

**Comment by 1000i100** [comment]
I will try https://www.npmjs.com/package/ics who handling duration. I'm following this issue to try back ical.js on next release.

**Comment by kewisch** [comment]
Released 1.3.0 with the latest changes. Let me know if any issues come up!
