### ISSUE TITLE
buffer.search

### ISSUE THREAD

**Issue by VincentBrule** [kewisch/ical.js#355]
Hi ! :)

When I run ICAL.pârse, I have the error "buffer.search doesn't exist".. Did you know this problem please ?

**Comment by elspru** [comment]
I have this problem also.

**Comment by elspru** [comment]
@VincentBrule what was the solution?

**Comment by roper79** [comment]
In my case, it was the mistake of reading the text file just by `readFileSync("file.ical")` instead of `readFileSync("file.ical", "utf8")`
