### ISSUE TITLE
[Question] explain differences between property.type and getDefaultType

### ISSUE THREAD

**Issue by skjnldsv** [kewisch/ical.js#374]
Hello @kewisch and thanks for your incredible work!
I'm wondering what are the difference between a `Property.type` and `Property.getDefaultType()`.
One return the proper type for me and the later often 'undefined'. :)

Have a happy holidays/Christmas/Hanoucca/New Year! :champagne:

**Comment by kewisch** [comment]
Better late than never, apologies for not getting back :)

`type` is the current type, and `getDefaultType` gives you the default type.

DTSTART;VALUE=DATE:20200101 would give you a date type, but a date-time default type.
