### ISSUE TITLE
Date range search from ical data

### ISSUE THREAD

**Issue by vijaysar** [kewisch/ical.js#375]
Hello iMozilla ical developers,

Is it possible to have a simple way to search a ICS payload for date range search like current date or current week etc.?  This will make it easy to pull in an ICS file or a caldav feed and present only current week events for example.

Thanks
Vijay

**Comment by kewisch** [comment]
I don't think we have a simple function to expand between dates, but the recurrence iterator can iterate up to the start and then give you instances between. It should be possible in consumer code, therefore I am closing this one for now.
