### ISSUE TITLE
A Hello World Example?

### ISSUE THREAD

**Issue by elspru** [kewisch/ical.js#376]
Hi, is it possible to make a simple example that works?

I haven't been able to put the tidbits together into something that works. 

here is my attempt:
```
'use strict';
const ICAL = require('ical.js');
const fs = require('fs');


/** loads calendar and prints it to console.
 * @param {string} filename */
function loadCalendar(filename) {
  fs.readFile(filename, (error, data) => {
    if (error) {
      console.log('error:' + error);
    }
    console.log('data: ' + data);
    console.log(ICAL.parse(data));
  });
}

loadCalendar('data/LiberIT.ics');
```

and here is the result:
```
vrenpces@hgaczo:~/services/pyatzo$ js calendar.js 
data: BEGIN:VCALENDAR
CALSCALE:GREGORIAN
PRODID:-//Example Inc.//Example Calendar//EN
VERSION:2.0
BEGIN:VEVENT
DTSTAMP:20080205T191224Z
DTSTART:20081006
SUMMARY:Planning meeting
UID:4088E990AD89CB3DBB484909
END:VEVENT
END:VCALENDAR

/home/vrenpces/services/pyatzo/node_modules/ical.js/build/ical.js:2160
    var lastPos = buffer.search(CHAR);
                         ^

TypeError: buffer.search is not a function
    at Function.ICAL.parse.parser._eachLine (/home/vrenpces/services/pyatzo/node_modules/ical.js/build/ical.js:2160:26)
    at Object.parser [as parse] (/home/vrenpces/services/pyatzo/node_modules/ical.js/build/ical.js:1731:12)
    at fs.readFile (/home/vrenpces/services/pyatzo/calendar.js:14:22)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by derekantrican** [comment]
@elspru If you look at this repository's README, there is a link to a JSFiddle that gives you a simple example: http://jsfiddle.net/kewisch/227efboL/

If you want to see a more full implementation, you can look at my repository here: https://github.com/derekantrican/GAS-ICS-Sync/blob/master/Code.gs (specifically the `ConvertToCustomEvent` function)

**Comment by enorms** [comment]
The JSFiddle is not running as [the ical URL points to a 404 error](https://rawgit.com/mozilla-comm/ical.js/master/build/ical.js). Searching for ical gives [a different implementation hosted at Cloudflare](https://cdnjs.cloudflare.com/ajax/libs/ical.js/1.3.0/ical.min.js), which does work. (I made a [working example on Codepen](https://codepen.io/ericafe/pen/jOERrzb).)

**Comment by ochov1** [comment]
hi.
the data that you are passing in the example is not the data that is in ics file. 
there is some methods to pass the data? 
thanks.

**Comment by kewisch** [comment]
I've fixed the jsfiddle. There is also a request for more docs in #419 that I am duping this against.
