### ISSUE TITLE
Parsing of VTIMEZONE happens improperly

### ISSUE THREAD

**Issue by derekantrican** [kewisch/ical.js#380]
JSFiddle to reproduce: http://jsfiddle.net/7f1q56mb/2/
ICAL link: http://ical.8to18.com/link/jacksonville/2018-2019/BBB%20V/EDT
Link better describing the issue on my repo: https://github.com/derekantrican/GAS-ICS-Sync/issues/23

Basically, ICAL.js is improperly intepreting the `VTIMEZONE` object of the above ICAL. The timezone is Eastern time. If you import the linked ICAL above into Google Calendar, Google Calendar will *properly* interpret the timezone, so I believe this to be a bug with ICAL.js

**Comment by nanobrad** [comment]
The vtimezone component in your sample data is incorrect.

Somehow, the daylight and standard have been reversed.

Daylight, tzoffsetfrom should be -0500, tzoffsetto, should be -0400.
Standard, tzoffsetfrom should be -0400, tzoffsetto, should be -0500.

If you make that correction to the sample, then the output is correct.

[RFC 5545](https://tools.ietf.org/html/rfc5545) (page 67) has a sample record:
```
       BEGIN:DAYLIGHT
       DTSTART:20070311T020000
       RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
       TZOFFSETFROM:-0500
       TZOFFSETTO:-0400
       TZNAME:EDT
       END:DAYLIGHT
       BEGIN:STANDARD
       DTSTART:20071104T020000
       RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
       TZOFFSETFROM:-0400
       TZOFFSETTO:-0500
       TZNAME:EST
       END:STANDARD
```

**Comment by derekantrican** [comment]
Thanks for your help. Since this isn't a problem with ICAL.js, then I'm going to close this
