### ISSUE TITLE
Parser splits vCard ADR parameter "LABEL" at comma despite quoting (when it appears after multi-value parameter "TYPE")

### ISSUE THREAD

**Issue by caugner** [kewisch/ical.js#386]
While investigating [an issue](https://github.com/nextcloud/contacts/issues/1009), I noticed that the ical.js parser seems to split values that contain a comma, even if the value is quoted or the comma escaped.

This causes `ICAL.stringify.component` to fail on the parsed jCal object.

**Update**: I had a look [at the `ADR` section](https://tools.ietf.org/html/rfc6350#section-6.3.1) in the RFC 6350:

> Where it makes semantic sense, individual text components can include multiple text values (e.g., a "street" component with multiple lines) separated by the COMMA character (U+002C).

This makes me think that actually the text parsing itself is correct, but rather `ICAL.stringify.property` should convert the Array back into a `string` [at this location](https://github.com/mozilla-comm/ical.js/blob/v1.3.0/lib/ical/stringify.js#L126-L128), rather than calling `ICAL.stringify._rfc6868Unescape(value)` with `value` being an `Array` (that doesn't have the `replace` function and causes the `TypeError`).

### Input

```js
var input = `BEGIN:VCARD
VERSION:4.0
ADR;TYPE=home;LABEL="Test 42, Berlin":;;Test 42\, Berlin;;;;
END:VCARD
`;

var jCal = ICAL.parse(input);
console.dir(jCal);

var vcard = ICAL.stringify.component(jCal);
console.log(vcard);
```

### Actual result

```js
[
  "vcard",
  [
    ["version",{},"text","4.0"],
    ["adr",{"type":"home","label":["Test 42"," Berlin"]},"text",["","",["Test 42"," Berlin"],"","","",""]]],
    []
]

// Uncaught TypeError: t.replace is not a function
//     at Function.r._rfc6868Unescape (ical.js:1657)
//     at Function.r.property (ical.js:1493)
//     at Function.r.component (ical.js:1444)
```

### Expected result

```js
[
  "vcard",
  [
    ["version",{},"text","4.0"],
    ["adr",{"type":"home","label":"Test 42, Berlin"},"text",["","","Test 42, Berlin","","","",""]]],
    []
]

// BEGIN:VCARD
// VERSION:4.0
// ADR;TYPE=home;LABEL="Test 42, Berlin":;;Test 42\, Berlin;;;;
// END:VCARD
```

**Comment by RuralYak** [comment]
@kewisch PTAL at https://github.com/mozilla-comm/ical.js/pull/387
