### ISSUE TITLE
Not working with angular 8 in production mode

### ISSUE THREAD

**Issue by konsultaner** [kewisch/ical.js#394]
I used ICAL in my angular 6/7 project. After updating to angular 8 I got the error `Uncaught ReferenceError: ICAL is not defined`. When removing ICAL, The application works fine. I imported it like this:

```ts
import * as ICAL from 'ical.js';
```

Is there something wrong with this code?

```js
if (typeof module === 'object') {
  // CommonJS, where exports may be different each time.
  ICAL = module.exports;
} else if (typeof ICAL !== 'object') {/* istanbul ignore next */
  /** @ignore */
  this.ICAL = {};
}
```

**Comment by konsultaner** [comment]
Work around:

Add this to your `polyfills.ts`
```ts
(window as any).ICAL = {};
```

**Comment by kewisch** [comment]
There is a lot wrong with the module loader :) I'm thinking whatever we do in #329 will fix this.
