### ISSUE TITLE
Should a recurrence be able to have a duration specified?

### ISSUE THREAD

**Issue by epicfaace** [kewisch/ical.js#396]
It looks like that is the case from https://tools.ietf.org/html/rfc5545#section-3.8.5.3

> If the duration of the recurring component is specified with the
      "DTEND" or "DUE" property, then the same exact duration will apply
      to all the members of the generated recurrence set.  Else, if the
      duration of the recurring component is specified with the
      "DURATION" property, then the same nominal duration will apply to
      all the members of the generated recurrence set and the exact
      duration of each recurrence instance will depend on its specific
      start time.  For example, recurrence instances of a nominal
      duration of one day will have an exact duration of more or less
      than 24 hours on a day where a time zone shift occurs.  The
      duration of a specific recurrence may be modified in an exception
      component or simply by using an "RDATE" property of PERIOD value
      type.

If so, is that something that's missing from this library? Should it be added to https://mozilla-comm.github.io/ical.js/api/ICAL.Recur.html ?

**Comment by georgehrke** [comment]
@epicfaace This library supports both RDATE as well as recurrence-ids (for recurrence exception).

Please take note that you should not call ICAL.Recur directly but use `ICAL.Event::iterator` instead:
https://github.com/mozilla-comm/ical.js/blob/master/lib/ical/event.js#L278

(ICAL.Recur only represents exactly one RRULE property. It does not do any recurrence expansion on its own)
