### ISSUE TITLE
Could not parse Duration with only "P" character

### ISSUE THREAD

**Issue by duyhotan2000** [kewisch/ical.js#400]
Hi,

When I use ical.js to parse VALARM object via `getFirstValue` function, I got an error: **'invalid duration value: Not enough duration components in '**.

I found that the `icalduration_from_string` function could not parse the duration with only "P" (mean 0).

In this case, I think we need to return ICalDuration object with all zero values.

What do you think?

**Comment by kewisch** [comment]
Can you link to where just `P` is allowed? IIRC then there must be some quantifier, 0 would require `PT0S` for example

**Comment by duyhotan2000** [comment]
There is no document noted about this but should we also cover this case?

**Comment by georgehrke** [comment]
@duyhotan2000 Please see the definition of [duration value in RFC5545](https://tools.ietf.org/html/rfc5545#section-3.3.6)

It's pretty strict: The `P` needs to be followed by either `dur-date`, `dur-time` or `dur-week`.
An empty value is not allowed.

**Comment by kewisch** [comment]
This should only be implemented if the rfc allows for it, which it doesn't as Georg noted. Thanks for the report though!

**Comment by georgehrke** [comment]
@duyhotan2000 As a recommendation from my side:
- If you have control over the program generating the faulty period, fix it there.
- Otherwise just replace it before parsing, like `icalString.replace(/^TRIGGER:P$/gm, 'TRIGGER:P0D')`
