### ISSUE TITLE
Remove build artifacts from tree

### ISSUE THREAD

**Issue by kewisch** [kewisch/ical.js#405]
I used to like having build/ical.js and sorts in the tree because it was easy to get started and just grab the file. I've since changed my mind, the constant browser builds and differences in minification have been pretty annoying. I'm removing the artifacts now. 

I'm later going to set up automation so that when publishing to NPM there is an ical.js file to use. I'll also have to figure out if this breaks the cdnjs integration.

**Comment by twinklebob** [comment]
This has broken the jsFiddle and validator which both used the version from the build folder. I agree with moving them from source control, but you now need to have another version available for testing.

**Comment by kewisch** [comment]
Got it, thanks for the note. I'll find a solution for that soon, possibly when I have automation set up. Maybe I can have it link to the latest artifact from github actions.

**Comment by kewisch** [comment]
With unpkg and new automation, we should be good now.
