### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by mmso** [kewisch/ical.js#416]
Hi!

Thanks for the library. The latest version 1.3.0 was released a while ago in https://github.com/mozilla-comm/ical.js/commit/3f219e04f238bcad6c964e8d93b21de49e5f5047.

Are you planning to release a new version soon? There are some fixes that we would like to have in our projects, in particular https://github.com/mozilla-comm/ical.js/commit/7b8d59d6cded33d08da617ca42696755fadd6587

**Comment by kewisch** [comment]
Most certainly! I wanted to get some of the last pull requests in before I do.

**Comment by Timebutt** [comment]
Any news on this new release? 👀

**Comment by skjnldsv** [comment]
Bump :)

**Comment by PaulMorris** [comment]
Closing since 1.4.0 has now been released: https://github.com/mozilla-comm/ical.js/releases/tag/v1.4.0
