### ISSUE TITLE
Example.

### ISSUE THREAD

**Issue by ochov1** [kewisch/ical.js#419]
Hi. 

I am trying to use this, I am not  using very offen javascript.
how to pass the data.

I saw examples on JSFiddle, 
var iCalendarData = [
    'BEGIN:VCALENDAR',
    'CALSCALE:GREGORIAN',
    'PRODID:-//Example Inc.//Example Calendar//EN',
    'VERSION:2.0',
    'BEGIN:VEVENT',    
    'DTSTAMP:20080205T191224Z',
    'DTSTART:20081006',
    'SUMMARY:Planning meeting',
    'UID:4088E990AD89CB3DBB484909',
    'END:VEVENT',
    'END:VCALENDAR'
].join("\r\n");

but in the ics file, the info is very different.

so how can I pass the data?

I need it inside of an app and I cant pass files.

thank you.

**Comment by dilyanpalauzov** [comment]
https://github.com/mozilla-comm/ical.js/wiki/Parsing-basic-iCalendar provides an example:
```javascript
// Get the basic data out
var jCalData = ICAL.parse(someICalData);
var comp = new ICAL.Component(jCalData[1]);
```

I had to use on the last line `new ICAL.Component(jCalData)` without `[1]` to make it working for me.

**Comment by dilyanpalauzov** [comment]
I do not see why in the ICS file the information shall be very different.
