### ISSUE TITLE
nextcloud login

### ISSUE THREAD

**Issue by guitar9** [kewisch/ical.js#422]
Hello thank you for this library.
Can I use this to build a nextcloud calendar client?
I dont know to handle auth with nextcloud? 
Somebody has an example?

**Comment by georgehrke** [comment]
Hello,

> Can I use this to build a nextcloud calendar client?

ical.js is only for parsing / modifying / creating / serialising iCalendar data as specified in [RFC5545](https://tools.ietf.org/html/rfc5545).
If you want to build a Nextcloud calendar client, you will also need some library that helps you with CalDAV.

> I dont know to handle auth with Nextcloud?

For the matter of CalDAV, simple Basic Auth is enough.

**Comment by dilyanpalauzov** [comment]
Can this ticket be closed, as it is not ical.js related?
