### ISSUE TITLE
jsfiddle playground cannot import library 

### ISSUE THREAD

**Issue by AbleLincoln** [kewisch/ical.js#425]
**Problem:** The [jsfiddle](http://jsfiddle.net/kewisch/227efboL/) imports the library via [rawgit](https://rawgit.com/) which has been deprecated. This makes the jsfiddle unusable.

**Solution:** import the library from a more reliable source like [cdnjs](https://cdnjs.com/libraries/ical.js)

**Comment by AbleLincoln** [comment]
I just realized this issue is also happening with the validator

**Comment by kewisch** [comment]
Updated the jsfiddle to use unpkg and the validator in d17f39b18e2600c9a3544ed29ac0a45ab1203015
