### ISSUE TITLE
Latest release is missing a dist/build folder

### ISSUE THREAD

**Issue by rutgerv90** [kewisch/ical.js#430]
Hi, 

The new release is missing a dist/build folder with the distribution files i.e. `ical.js/build/ical.min.js`

**Comment by skjnldsv** [comment]
Hum, I do :thinking: 

```sh
$ ls -la node_modules/ical.js/build
total 364
drwxr-xr-x 2 admin users   4096  7 april 13:28 .
drwxr-xr-x 4 admin users   4096  7 april 13:28 ..
-rw-r--r-- 1 admin users 279688 26 oct.   1985 ical.js
-rw-r--r-- 1 admin users  81375 26 oct.   1985 ical.min.js
```

**Comment by svanstrom** [comment]
Yeah, this is a real issue.

Why is it still not fixed almost two months later?

**Comment by kewisch** [comment]
Can you provide steps to reproduce this? I did `yarn install ical.js` and can see ical.js and ical.min.js like @skjnldsv.

**Comment by kewisch** [comment]
Please open a new issue if this is still the case, I can't seem to reproduce.
