### ISSUE TITLE
Add a multi-value with addPropertyWithValue

### ISSUE THREAD

**Issue by radarfox** [kewisch/ical.js#436]
Is it possible to add multiple values by this method? For example, to EXDATE where you can add a comma delimited list of dates. I would expect something like this to work:

```
const vevent = new ICAL.Component('vevent');
vevent.addPropertyWithValue([new ICAL.Time({year: 2020}), new ICAL.Time({year: 2021})]);
```

But this will produce the following error:

```
TypeError: property[0].toUpperCase is not a function
```

I ended up using the lower-level method:

```
function createExdateProperty (times) {
  const strings = times.map((time) => time.toICALString());
  return new this.ICAL.Property(['exdate', {}, 'date-time', ...strings]);
}
```

Maybe would you consider adding something like `addPropertyWithMultiValue`, or allow to pass an array to `addPropertyWithValue`, for the multi-value components?

**Comment by kewisch** [comment]
Not possible with that function. if `times` are ICAL.Property already you want:

```
const vevent = new ICAL.Component('vevent');
const exdate = new ICAL.Property('exdate');
exdate.setValues(times);
vevent.addProperty(exdate);
```

**Comment by kewisch** [comment]
Added example to https://github.com/kewisch/ical.js/wiki/Creating-iCalendar
