### ISSUE TITLE
What is the purpose of `zone` and `timezone` both exist in `dtstart`?

### ISSUE THREAD

**Issue by piavgh** [kewisch/ical.js#444]
When using `console.log` on `dtstart` value, I usually see 2 fields:

```
{
  ...
  timezone: 'Asia/Ho_Chi_Minh',
  zone:
   { wrappedJSObject: [Circular],
     expandedUntilYear: 0,
     changes: [],
     tzid: 'floating' } }
  ...
```

Why do you need `zone` property if it already has the `timezone`?

Thanks. @asutherland @kewisch

**Comment by kewisch** [comment]
Certainly some ambiguity, one is the tzid, the other is the actual zone object if one is associated. Closing this issue unless you feel there are any improvements we can make.
