### ISSUE TITLE
cannot be used in type="module" mode

### ISSUE THREAD

**Issue by TimDaub** [kewisch/ical.js#449]
Hi,

I'm using [microbundle](https://github.com/developit/microbundle) to include "ical.js". It's `modern` and `module` options allow to include the bundled js as a `<script type="module" src="bundle.js"></script>`

However, when I start my application, I get the following error:

```js
Uncaught ReferenceError: assignment to undeclared variable ICAL
```

this is because `ICAL` is never officially initialized. 

https://github.com/mozilla-comm/ical.js/blob/dcfe5a67527e73f54db21fbc31f23670a29704b8/lib/ical/helpers.js#L11

Now, in a normal environment `<script src="bundle.js"></script>`, this wouldn't be a problem as strict mode isn't enabled by default. For Javascript modules though, [strict mode is always on](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode):

> ECMAScript 2015 introduced JavaScript modules and therefore a 3rd way to enter strict mode.  The entire contents of JavaScript modules are automatically in strict mode, with no statement needed to initiate it.

I'm not sure how to handle this exactly, but a naive guess would have been to do further feature-detection. E.g. of ES6 modules. [SO has an idea.](https://stackoverflow.com/questions/27922232/how-to-feature-detect-es6-modules)

**Comment by kewisch** [comment]
#470
