### ISSUE TITLE
`status` is not available as property on new ICS.Event component

### ISSUE THREAD

**Issue by TimDaub** [kewisch/ical.js#452]
Section in RFC: https://tools.ietf.org/html/rfc5545#section-3.8.1.11

```
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
PRODID:-//Example Inc.//Example Calendar//EN
VERSION:2.0
BEGIN:VEVENT
DTSTAMP:20080205T191224Z
DTSTART:20081006
SUMMARY:Planning meeting
STATUS: CONFIRMED
UID:4088E990AD89CB3DBB484909
END:VEVENT
END:VCALENDAR
```

```js
var iCalendarData = "BEGIN:VCALENDAR" + /* ... */ + "END:VCALENDAR";
var jcalData = ICAL.parse(iCalendarData);
var comp = new ICAL.Component(jcalData);
var vevent = comp.getFirstSubcomponent("vevent");
var event = new ICAL.Event(vevent);
assert(event.status === "CONFIRMED")
// assertion fails as status is not available as a property
assert(event._firstProp("status") === "CONFIRMED")
// true
```

Any ideas how to fix this? I see that it's available in the EVENT item...

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords

> Reserved words actually only apply to Identifiers (vs. IdentifierNames) . As described in es5.github.com/#A.1, these are all IdentifierNames which do not exclude ReservedWords.

According to my judgment, that means that `event.status` is a legitimate usage of the name "status" as an "IdentifierName".

**Comment by dilyanpalauzov** [comment]
There are ICAL.Component and ICAL.Event.  The former provides common set of options to all ICalendar components (VTODO, VJOURNAL, VFREEBUSY, VAVAILABILITY, VEVENT), the latter facilitates the access to some properties of VEVENT.   Accessing and parsing DTSTART, RRULE, and some more are handled by ICAL.Event.  Simple properties like URL, STATUS are handled by ICAL.Component.  LOCATION and SUMMARY are also “simple” properties, that are handled by ICAL.Event (for some reason).  You can access STATUS using ICAL.Component:
```javascript
comp.getFirstPropertyValue('status').toUpperCase() === 'CONFIRMED'
```

**Comment by TimDaub** [comment]
Great, thanks
