### ISSUE TITLE
exdate doesn't support dates

### ISSUE THREAD

**Issue by mifi** [kewisch/ical.js#458]
See this example:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ddaysoftware.com//NONSGML DDay.iCal 1.0//EN
BEGIN:VEVENT
DTEND:20201110T110000
DTSTAMP:20201102T160712Z
DTSTART:20201110T080000
EXDATE:20201126,20201127
RRULE:FREQ=WEEKLY;BYDAY=MO,TH
SEQUENCE:0
UID:652ea16f-d20f-472b-b906-191e5339cf55
END:VEVENT
END:VCALENDAR
```

It crashes with:

```
     Error: invalid date-time value: "2020-11-26T::"
      at Function.ICAL.Time.fromDateTimeString (node_modules/ical.js/build/ical.js:5901:13)
      at Object.decorate (node_modules/ical.js/build/ical.js:781:28)
      at Property._decorate (node_modules/ical.js/build/ical.js:2939:47)
      at Property._hydrateValue (node_modules/ical.js/build/ical.js:2922:44)
      at Property.getFirstValue (node_modules/ical.js/build/ical.js:3068:19)
```

I believe the code doesn't support dates without a time. The same happens with just one date
`EXDATE:20201126`

According to [this spec](https://icalendar.org/iCalendar-RFC-5545/3-8-5-1-exception-date-times.html), exdate should support dates, as far as I understood it.

```
exdtval    = date-time / date
```

**Comment by rutledgek** [comment]
Thanks, I posted the linked to issue.  The Ical content is generated by our backend and works with calendar applications.  The item errors out whether it is a comma-separated list of dates or just a single date.  It looks like the js attends to append a Time to it.  The expected outcome of a single date is that it would exclude all days in the list from midnight to midnight of the dates listed.

**Comment by mifi** [comment]
Gotcha. Updating issue

**Comment by tasn** [comment]
I also got bit by it. :(

Here's the event:
```
BEGIN:VEVENT
SUMMARY:Test
UID:5b6d0619fd754144b1ad09b0a95841401601993113647
CATEGORY_COLOR:-12703179
CATEGORIES:Work
LAST-MODIFIED:20201006T140513Z
DTSTART:20201005T150000Z
DTEND:20201005T160000Z
STATUS:CONFIRMED
RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=MO
EXDATE:20201012
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-P0DT1H0M0S
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-P1DT0H0M0S
END:VALARM
END:VEVENT
```
To reproduce:
```js
// eventContent is the above event.
const parsed = ICAL.parse(eventContent);
const comp = new ICAL.Component(parsed);
console.log(comp.getFirstPropertyValue('exdate'));
```

**Comment by tasn** [comment]
Maybe #438 fixes this issue? Looks related.

**Comment by kewisch** [comment]
Note that `EXDATE` does support both, but you need to specify the type. The default type is `DATE-TIME`, so you'd need:

`EXDATE;VALUE=DATE:20201126,20201127`
