### ISSUE TITLE
Empty RDATE causes error

### ISSUE THREAD

**Issue by christopher-siegel** [kewisch/ical.js#462]
A .ics file i'm trying to import into NextCloud Calendar is causing this issue (related to ical.js):

```
Error: invalid date-time value: "--T::"
    at Function.ICAL.Time.fromDateTimeString (ical.js:5901)
    at Object.decorate (ical.js:781)
    at t._decorate (ical.js:2939)
    at t._hydrateValue (ical.js:2922)
    at t.getFirstValue (ical.js:3068)
    at Function.value (property.js:458)
    at Function.value (abstractComponent.js:544)
    at Function.value (abstractComponent.js:550)
    at Function.value (abstractComponent.js:550)
    at Function.value (calendarComponent.js:144)
```

**The .ics file has empty RDATE: entries – is this okay? Since i can't fix the exported ICS file of the univercity calendar, would it be possible for ical.js to ignore empty RDATE entries completly?**

This is what part of the ics file looks like:

```
TZOFFSETTO:+0200
DTSTART:19160430T230000
RDATE:
RDATE:
RDATE:
RDATE:
RDATE:
RDATE:
RDATE:
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19161001T010000
RDATE:
RDATE:
RDATE:
RDATE:
RDATE:
END:STANDARD
BEGIN:DAYLIGHT
```

**Comment by christopher-siegel** [comment]
Looks like in ical.js line 729 this happens:
```
"date-time": {
      fromICAL: function(aValue) {
        // from: 20120901T130000
        // to: 2012-09-01T13:00:00
        if (!design.strict && aValue.length == 8) {
          // This is probably a date, e.g. 20120901
          return icalValues.date.fromICAL(aValue);
        } else {
          var result = aValue.substr(0, 4) + '-' +
                       aValue.substr(4, 2) + '-' +
                       aValue.substr(6, 2) + 'T' +
                       aValue.substr(9, 2) + ':' +
                       aValue.substr(11, 2) + ':' +
                       aValue.substr(13, 2);

          if (aValue[15] && aValue[15] === 'Z') {
            result += 'Z';
          }

          return result;
        }
      },
```

There is no check if aValue even has any length. It only ever checks if it has a length of exactly 8, otherwise it just builds a dateTimeString by using substr on aValue (which is an empty string in my case). 

Because of that result = "--T::".

There are a few other points where this happens and substr is used without any checks.

What could be a solution here?
Just add 0000-00-00T00:00:00 as a placeholder? or catch empty dates later?

**Comment by castaway** [comment]
RDATE is a DATE-TIME type, and as far as I can see that's not allowed to be empty: https://tools.ietf.org/html/rfc5545#page-120, 
https://tools.ietf.org/html/rfc5545#page-32
