### ISSUE TITLE
Mishandling of escaped quotes in attendee names

### ISSUE THREAD

**Issue by thexeos** [kewisch/ical.js#482]
Running this through [validator](https://mozilla-comm.github.io/ical.js/validator.html) returns mangled output:

```
BEGIN:VCALENDAR
BEGIN:VEVENT
ATTENDEE;CN="Firstname \"Nickname\" Lastname";PARTSTAT=NEEDS-ACTION:/id/
END:VEVENT
END:VCALENDAR
```

One result of this is inconsistent display of participant names in Thunderbird:

In the email viewer itself (for emails with ICS attachment), the preview box cuts off attendee name at first escape character (backslash):
![image](https://user-images.githubusercontent.com/2260539/142294504-7e94c086-3e2b-4bb9-b013-dcd456c5f847.png)

After adding event to calendar, the event details window captures text beyond the semicolon:
![image](https://user-images.githubusercontent.com/2260539/142294589-819a5c3e-e20a-4ebe-b5d0-85da064dd0e8.png)

**Comment by dilyanpalauzov** [comment]
The correct [RFC6868](https://datatracker.ietf.org/doc/html/rfc6868)-presentation of the above data is `ATTENDEE;CN=Firstname ^'Nickname^' Lastname;PARTSTAT=NEEDS-ACTION:/id/`.

The problem report does not describe how to reproduce the problem.  In particular it is unclear, whether ical.js has problems parsing `ATTENDEE;CN="Firstname \"Nickname\" Lastname";PARTSTAT=NEEDS-ACTION:/id/` as input, or if ical.js returns `ATTENDEE;CN="Firstname \"Nickname\" Lastname";PARTSTAT=NEEDS-ACTION:/id/` as output.

As far as the above text is used as input to the validator, the input is wrong.

https://github.com/mozilla-comm/ical.js/pull/507 does improve handling of parsing of parameter values with ^-escapes.

**Comment by ray007** [comment]
I think I have a related problem: parsing events from ics data I get an `ICAL.Event` with a `color` property set to `"rgb(81\\,114\\,60)"`.
Shouldn't there be some decode/encode on parsing/serializing?

**Comment by kewisch** [comment]
I'm not 100% sure this is a bug or works as intended. What @dilyanpalauzov says seems to suggest everything is working properly? Would appreciate a reopen or new issue in case I missed something.
