### ISSUE TITLE
Latest version on npm (1.4.0) build -> assignment to undeclared variable ICAL

### ISSUE THREAD

**Issue by notKamui** [kewisch/ical.js#488]
In some strict configuration setups such as rollup or Vite, ical.js provokes an error :

`Uncaught ReferenceError: assignment to undeclared variable ICAL`

Indeed, with a quick look at the beginning of the build we see this :

```js
/* istanbul ignore next */
/* jshint ignore:start */
if (typeof module === 'object') {
  // CommonJS, where exports may be different each time.
  ICAL = module.exports;
} else if (typeof ICAL !== 'object') {/* istanbul ignore next */
  /** @ignore */
  this.ICAL = {};
}
```

ICAL is assigned even though it hasn't been declared. Now, the current source code does fix this by adding a `var ICAL;` at the beginning ; but the current build on npm doesn't. This causes problems with libraries that depends on this one, with Svelte for example. 

Will the current source code be pushed to npm ?

Thank you in advance

**Comment by kewisch** [comment]
I've release 1.5.0 with the update from #470 that should rectify the var assignment.

**Comment by notKamui** [comment]
Perfect!
