### ISSUE TITLE
Remove E4X

### ISSUE THREAD

**Issue by lightsofapollo** [kewisch/ical.js#5]
Remove "for each" /  E4X xml stuff

@kewisch What do you think? I think this lib is very valuable outside of a gecko environment at minimum I would like to have it working in chrome/node/firefox/b2g.

Also I believe this throw errors while in strict mode which is on by default in b2g dev mode.

**Comment by kewisch** [comment]
Yes, e4x can go for now. The idea behind this was to implement [rfc6321](http://tools.ietf.org/html/rfc6321), but given e4x is not supported outside of Firefox and its also on the chopping block, I think we should remove the code for now and when the json<->rfc5545 parser is most stable then we can reconsider implementing xCal.
