### ISSUE TITLE
ical.timezones.js fails to parse timezones 

### ISSUE THREAD

**Issue by kbalasub** [kewisch/ical.js#510]
Build ical.js from source using grunt package-zones. The load of ical.timezones.js throws an exception that it is unable to parse the timezones. This is because the line below 

ICAL.TimezoneService.register(ICAL.Component.fromString("BEGIN:VTIMEZONE\r\n" + tzdata + "END:VTIMEZONE")) };

needs to be changed to 

ICAL.TimezoneService.register(ICAL.Component.fromString("BEGIN:VTIMEZONE\r\n" + tzdata + "\r\nEND:VTIMEZONE")) };

**Comment by kewisch** [comment]
Thanks, taken care of in said commit!

**Comment by xeruf** [comment]
that seems very windows-y, sure that should not be the generic OS line separator?
