### ISSUE TITLE
TypeError Cannot read properties of undefined (reading 'toString') in getOccurrenceDetails

### ISSUE THREAD

**Issue by zomars** [kewisch/ical.js#514]
Any pointers on why this might be happening?
```
 TypeError [22m Cannot read properties of undefined (reading 'toString')
error stack:[24m[22m
• ical.js:9004 getOccurrenceDetails
node_modules/ical.js/build/ical.js:9004:27
• 4270.js:244 <anonymous>
```

One of our users is using Zoho calendar and it seems like this error pops up when parsing a recurring event:

https://github.com/mozilla-comm/ical.js/blob/1fca94408148d75ffcbb666814890651da9f1c67/lib/ical/event.js#L200-L201

**Comment by dilyanpalauzov** [comment]
Please provide concise instructions how to reproduce the problem.

**Comment by kewisch** [comment]
I'm going to close this issue given there has been no response, if this is still an issue please reopen or create a new issue. Thanks for reporting!
