### ISSUE TITLE
Link to the docs is broken

### ISSUE THREAD

**Issue by handeyeco** [kewisch/ical.js#521]
On the GH page there's a link which takes people to a 404: http://mozilla-comm.github.com/ical.js/

Changing the `.com` to `.io` shows a blank page: https://mozilla-comm.github.io/ical.js/

Is there a canonical place to see the docs?

**Comment by kewisch** [comment]
It appears there are some issues with https://documentup.com/ which are hopefully resolved soon.

If you want to check out the API documentation see https://kewisch.github.io/ical.js/api/

(note also I recently moved the repository back to my own user)

**Comment by dilyanpalauzov** [comment]
Can this be closed?

**Comment by kewisch** [comment]
I need to replace documentup to close this. It still appears broken, so the service is no longer available. A static site is more than sufficient, I'll just have to change the build process to generate it. Waiting until #538 is merged

**Comment by biskweet** [comment]
Bumping this issue as it is still a problem

**Comment by kewisch** [comment]
I've simply redirected to the API docs and removed documentup. It turns out documentup.min.js was a random github HTML file, looks like I just wget'd it without looking. However, documentup basically showed the readme, and the api docs do that as well.
