### ISSUE TITLE
Cannot use proper REV values with vCARD 3.0

### ISSUE THREAD

**Issue by dilyanpalauzov** [kewisch/ical.js#540]
In VCARD 3.0 the REV property has the format:

> REV:1995-10-31T22:27:10Z

In VCARD 4.0 the REV property has the format:

> REV:19951031T222710Z

For me it seems impossible to add a property of format YYYY-MM-DDTHH:MM:SSZ to using `.addPropertyWithValue()` as the value is always converted to the YYYYMMDDTHHMMSSZ format.  But I want to create VCARD 3.0.

**Comment by kewisch** [comment]
@dilyanpalauzov do you have a test case for this? I tried this with both 3.0 and 4.0 and it seems to simply add it with the format advised?

```javascript
    let x = ICAL.parse("BEGIN:VCARD\nVERSION:3.0\nEND:VCARD");
    let comp = new ICAL.Component(x);

    comp.addPropertyWithValue("rev", "1995-10-31T22:27:10Z");
    console.log(comp.toJSON());
```

**Comment by dilyanpalauzov** [comment]
As far as I remember the problem was that it was not possible to specify, if the output shall be VCARD 3.0 or 4.0.

**Comment by kewisch** [comment]
Looking at https://www.rfc-editor.org/rfc/rfc2425 section 5.8.4, it looks like vcard3 "date", "time", and "date-time" values are defined as: "value types is based on a subset of the definitions in ISO 8601 standard". The examples also provide `19960811T123456Z`. REV in rfc2426 doesn't put any further restrictions on the subset, it simply says "single date-time value".

Therefore I would say YYYYMMDDTHHMMSSZ is a valid vcard3 format. Did I get that right?
