### ISSUE TITLE
Define JS compat

### ISSUE THREAD

**Issue by lightsofapollo** [kewisch/ical.js#56]
I am 100% sure ICAL.js does not work (Time likely does not work) with IE8. I personally don't have a stake there. I think we should conform to ES5 (whatever is 100% ES5 will run ICAL.js).

**Comment by kewisch** [comment]
Right now we are compatible to IE9 due to the getters and setters. I don't think we should introduce new js features unless it will make it significantly nicer, or bring better performance. When that time comes, we can use Babel or something like that. Not much to do in this issue though.
