### ISSUE TITLE
Change snake_case to camelCase

### ISSUE THREAD

**Issue by lightsofapollo** [kewisch/ical.js#6]
@kewisch 

I have seen both is_by_count and addComponent I personally prefer addComponent (camelCase over snake_case)

I am willing to offer bribes to move to 2 spaces over 4 as well :)

**Comment by kewisch** [comment]
snake_case is mostly from code that originates from libical, while camelCase was done for functions that I gave the same name as the functions in Lightning .idl files.

I personally like camelCase also so I wouldnt' mind moving all functions to it. I'm also fine with 2 spaces.

**Comment by kewisch** [comment]
We've switched to 2 spaces, I've updated the title to reflect the issue.
