### ISSUE TITLE
Figure out how to best handle the VALUE parameter

### ISSUE THREAD

**Issue by kewisch** [kewisch/ical.js#63]
When using ICAL.js in Lightning, I try to just forward the methods from the xpcom interface to ICAL.js. One of the cases that don't work out is get/set/removeParameter. Lightning interfaces were written with iCalendar in mind, so  `prop.getParameter("VALUE");` is a valid thing to do. This doesn't translate well to ICAL.js since the value type is no longer a real parameter.

On one hand, the API is correct if based on jCal, since VALUE is not a real parameter. On the other hand, developers used to iCalendar could expect it to be returned, so we might want to add special case code if the VALUE parameter is requested:
- **getParameter**: Return the type, iff the default type does not match the current type
- **setParameter**: don't set the parameter in jCal, instead call `resetType()` attempting to preserve the property value
- **removeParameter**: call `setParameter('value', defaultType)`, which will remove it at least for getParameter's eyes.

**Comment by lightsofapollo** [comment]
This makes sense to me... I prefer the jCal representation but thats is a bit early yet :)

**Comment by kewisch** [comment]
I'm deciding against this now. We are following jCal everywhere, so we shouldn't be special casing.
