### ISSUE TITLE
validator not able to find ICAL

### ISSUE THREAD

**Issue by dantagg** [kewisch/ical.js#643]
When I try and run any ical file in the online validator at https://kewisch.github.io/ical.js/validator.html, I get the following error
```
Couldn't parse as iCalendar:
Error: ReferenceError: ICAL is not defined
Filename: https://kewisch.github.io/ical.js/validator.html
Line: 49
Stack: validate@https://kewisch.github.io/ical.js/validator.html:49:17
onsubmit@https://kewisch.github.io/ical.js/validator.html:1:8
```
I think it is because unpkg is returning a 404 for the file https://unpkg.com/ical.js `src`ed on line 20

**Comment by kewisch** [comment]
Confirmed it works now :) https://kewisch.github.io/ical.js/validator.html
