### ISSUE TITLE
ParserError with ICAL.parse() Empty parameter name in

### ISSUE THREAD

**Issue by gstlouisgit** [kewisch/ical.js#645]
I have been working with ical and it is looking good when looping through my events.  However, the script halted on one of the vevents and I'm not too sure why.  This was a google invite from google themselves.

I am wondering if this would be because on line: 2061 it is having trouble with the terrible line at the end of the ALTREP?  It feels like it is a little related to bug 612.  However its worth noting I am using the code from cdn [https://unpkg.com/ical.js](url) because I am just using plain app with javascript.  This is version 1.5

below is the event properties **( I've tried to mask any personal info and emails with **domain** )**

BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:America/Detroit
BEGIN:DAYLIGHT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
TZNAME:EDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
TZNAME:EST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20230615T173211Z
LAST-MODIFIED:20230619T122252Z
DTSTAMP:20230619T122252Z
UID:0s7l7bu11p61ed6banmbl5tt8u@google.com
SUMMARY:Google // domain : Google Ads Consultation
STATUS:CONFIRMED
ORGANIZER;CN=domain@google.com;SCHEDULE-AGENT=CLIENT:mailto:domain
 domain@google.com
ATTENDEE;RSVP=TRUE;CN=domain@gmail.com;PARTSTAT=NEEDS-ACTION;CUTYPE=INDIV
 IDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:domain@gmail.com
ATTENDEE;RSVP=TRUE;CN=domain@domain.ca;PARTSTAT=ACCEPTED;CUTYPE=INDI
 VIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:domain@domain.ca
ATTENDEE;RSVP=TRUE;CN=domain@google.com;PARTSTAT=ACCEPTED;CUTYPE=IN
 DIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:domain@google.c
 om
X-MOZ-LASTACK:20230619T122252Z
DTSTART;TZID=America/Detroit:20230616T113000
DTEND;TZID=America/Detroit:20230616T115500
X-GOOGLE-CONFERENCE:https://meet.google.com/zvh-igna-qxp
X-MICROSOFT-CDO-OWNERAPPTID:145243311
DESCRIPTION;ALTREP="data:text/html,Contact%3A%20domain%20domain%3Cbr%3
 EPhone%3A%201%206132552366%3Cbr%3EEmail%3A%20%3Ca%20href%3D%22mailto%3A
 tont%40firstaid4u.org%22%20target%3D%22_blank%22%domain%40firstaid4u.or
 g%3C%2Fa%3E%3Cbr%3E%3Cbr%3EEmail%20in%20case%20of%20rescheduling%20%3Ca%20h
 ref%3D%22mailto%3Ajakobheberling%40google.com%22%20target%3D%22_blank%22%3E
 domain%40google.com%3C%2Fa%3E%3Cbr%3E%3Cbr%3E-%3A%3A~%3A~%3A%3A~%3A
 ~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3
 A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A%3A~%3A~%3
 A%3A-%3Cbr%3EJoin%20with%20Google%20Meet%3A%20%3Ca%20class%3D%22moz-txt-lin
 k-freetext%22%20href%3D%22https%3A%2F%2Fmeet.google.com%2Fzvh-igna-qxp%22%3
 Ehttps%3A%2F%2Fmeet.google.com%2Fzvh-igna-qxp%3C%2Fa%3E%3Cbr%3EOr%20dial%3A
 %20(US)%20%2B1%20971-292-3308%20PIN%3A%20707221803%23%3Cbr%3EMore%20phone%2
 0numbers%3A%20%3Ca%20class%3D%22moz-txt-link-freetext%22%20href%3D%22https%
 3A%2F%2Ftel.meet%2Fzvh-igna-qxp%3Fpin%3D2428173691267%26amp%3Bhs%3D7%22%3Eh
 ttps%3A%2F%2Ftel.meet%2Fzvh-igna-qxp%3Fpin%3D2428173691267%26amp%3Bhs%3D7%3
 C%2Fa%3E%3Cbr%3E%3Cbr%3ELearn%20more%20about%20Meet%20at%3A%20%3Ca%20class%
 3D%22moz-txt-link-freetext%22%20href%3D%22https%3A%2F%2Fsupport.google.com%
 2Fa%2Fusers%2Fanswer%2F9282720%22%3Ehttps%3A%2F%2Fsupport.google.com%2Fa%2F
 users%2Fanswer%2F9282720%3C%2Fa%3E%3Cbr%3E%3Cbr%3EPlease%20do%20not%20edit%
 20this%20section.%3Cbr%3E-%3A%3A~%3A~%3A%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A
 ~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3
 A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A%3A~%3A~%3A%3A-":Contact: domain domainson\nPhone: 1 \nEmail: domain@domain.org\n\nEmail in cas
 e of rescheduling domain@google.com\n\n-::~:~::~:~:~:~:~:~:~:~:~:~:
 ~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-\nJoin with Goog
 le Meet: https://meet.google.com/zvh-igna-qxp\nOr dial: (US) +1 971-292-330
 8 PIN: 707221803#\nMore phone numbers: https://tel.meet/zvh-igna-qxp?pin=24
 28173691267&amp;hs=7\n\nLearn more about Meet at: https://support.domain.com/a/
 users/answer/domain\n\nPlease do not edit this section.\n-::~:~::~:~:~:~:~
 :~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
SEQUENCE:0
TRANSP:OPAQUE
X-MOZ-INVITED-ATTENDEE:mailto:domain@domain.ca
X-MOZ-RECEIVED-SEQUENCE:0
X-MOZ-RECEIVED-DTSTAMP:20230615T173213Z
X-MOZ-GENERATION:1
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
DESCRIPTION:Default Mozilla Description
END:VALARM
END:VEVENT
END:VCALENDAR

The ParserError is:

`message: "Empty parameter name in ';ALTREP=\"data:text/html,Contact%3A%20Clayton%20domain%3Cbr%3EPhone%3A%201%206132552366%3Cbr%3EEmail%3A%20%3Ca%20href%3D%22mailto%3Aclaytont%40firstaid4u.org%22%20target%3D%22_blank%22%3Eclaytont%40firstaid4u.org%3C%2Fa%3E%3Cbr%3E%3Cbr%3EEmail%20in%20case%20of%20rescheduling%20%3Ca%20href%3D%22mailto%3Ajakobheberling%40google.com%22%20target%3D%22_blank%22%3Ejakobheberling%40google.com%3C%2Fa%3E%3Cbr%3E%3Cbr%3E-%3A%3A~%3A~%3A%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A%3A~%3A~%3A%3A-%3Cbr%3EJoin%20with%20Google%20Meet%3A%20%3Ca%20class%3D%22moz-txt-link-freetext%22%20href%3D%22https%3A%2F%2Fmeet.google.com%2Fzvh-igna-qxp%22%3Ehttps%3A%2F%2Fmeet.google.com%2Fzvh-igna-qxp%3C%2Fa%3E%3Cbr%3EOr%20dial%3A%20(US)%20%2B1%20971-292-3308%20PIN%3A%20707221803%23%3Cbr%3EMore%20phone%20numbers%3A%20%3Ca%20class%3D%22moz-txt-link-freetext%22%20href%3D%22https%3A%2F%2Ftel.meet%2Fzvh-igna-qxp%3Fpin%3D2428173691267%26amp%3Bhs%3D7%22%3Ehttps%3A%2F%2Ftel.meet%2Fzvh-igna-qxp%3Fpin%3D2428173691267%26amp%3Bhs%3D7%3C%2Fa%3E%3Cbr%3E%3Cbr%3ELearn%20more%20about%20Meet%20at%3A%20%3Ca%20class%3D%22moz-txt-link-freetext%22%20href%3D%22https%3A%2F%2Fsupport.google.com%2Fa%2Fusers%2Fanswer%2F9282720%22%3Ehttps%3A%2F%2Fsupport.google.com%2Fa%2Fusers%2Fanswer%2F9282720%3C%2Fa%3E%3Cbr%3E%3Cbr%3EPlease%20do%20not%20edit%20this%20section.%3Cbr%3E-%3A%3A~%3A~%3A%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A~%3A%3A~%3A~%3A%3A-\":Contact: domain domain\\nPhone: 1 6132552366\\nEmail: domain@domain.org\\n\\nEmail in case of rescheduling domain@google.com\\n\\n-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-\\nJoin with Google Meet: https://domain.domain.com/domain\\nOr dial:  phone numbers: https://domainamp;hs=7\\n\\nLearn more about Meet at: https://domain9282720\\n\\nPlease do not edit this section.\\n-::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-'"

name: "ParserError"`

**Comment by kewisch** [comment]
Hmm maybe related to #613  ? There are also a few other PRs pending that might be fixing the issue from @dilyanpalauzov , could you try the code in those to see if that fixes the issue?
