### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by joshtrichards** [kewisch/ical.js#646]
https://github.com/kewisch/ical.js/compare/v1.5.0...HEAD

Mostly looking for already merged PR #517 since it'll help close a couple downstream issues - e.g.

nextcloud/contacts#1855
nextcloud/contacts#1297

Thanks!

**Comment by titanism** [comment]
@kewisch we are happy to help maintain this project, we're the team behind https://forwardemail.net and are using `ical.js` for some arbitrary things on our CalDAV server (we're an email host and the only 100% open-source privacy-focused service).  For maintaining our projects across @forwardemail @ladjs @cabin @expressjs @koajs etc. we use [np](https://github.com/sindresorhus/np).  If you're interested, simply grant us npm and GitHub access to the user `titanism`.

**Comment by titanism** [comment]
Also it looks like the following PR's are also necessary:

- [ ] https://github.com/kewisch/ical.js/pull/507
- [ ] https://github.com/kewisch/ical.js/pull/613
- [ ] https://github.com/kewisch/ical.js/pull/621
- [ ] https://github.com/kewisch/ical.js/pull/535
- [ ] https://github.com/kewisch/ical.js/pull/550
- [ ] https://github.com/kewisch/ical.js/pull/536
- [ ] https://github.com/kewisch/ical.js/pull/534
- [ ] https://github.com/kewisch/ical.js/pull/457
- [ ] https://github.com/kewisch/ical.js/pull/421
- [ ] https://github.com/kewisch/ical.js/pull/418

**Comment by titanism** [comment]
@joshtrichards just a heads up if we don't get collab/maintainer access from @kewisch we will be publishing our own version of this project under `@forwardemail/ical.js` soon

**Comment by kewisch** [comment]
For the record, I'm going to be adding @titanism as a maintainer. We're going to meet soon to chat on direction and process, and then I'm looking forward to a great future for ical.js! In the meanwhile, I've updated dependencies and made some comments on recent PRs, and I'll see if I can do an interim release towards the weekend. 🎉

**Comment by kewisch** [comment]
Super painless now with some action updates :) https://www.npmjs.com/package/ical.js/v/2.0.0

**Comment by titanism** [comment]
Heck yeah @kewisch !!! 🚀 🚀 🚀   🙏 Thank you for all this and so stoked - great work.
