### ISSUE TITLE
Code minification issues

### ISSUE THREAD

**Issue by jannikac** [kewisch/ical.js#699]
Hi, when using VSCode, right-clicking on a symbol and clicking `Go to definition` shows the minified code in newer VSCode versions (Versions after February 2024 (version 1.87)). At first I thought this might be a VSCode issue since it used to work in older versions. However a member of the project confirmed that it is working as intended in the newer versions of VSCode, older versions didnt read the `exports` field of `package.json` correctly: https://github.com/microsoft/TypeScript/issues/58589#issuecomment-2153234681.

I've read some posts about libaray design and according to [this](https://stackoverflow.com/questions/48673408/should-javascript-npm-packages-be-minified), npm packages should not be minified when no network transfers are used since minification just reduces the size of the transferred js. Without network transfers minification provides no benefit, it just makes debugging more complicated in development and has some other implications. This library currently exports minified packages no matter how it is used.
```json
"exports": {
    "import": "./dist/ical.min.js",
    "require": "./dist/ical.es5.min.cjs"
},
```

Therefore I believe exports should not be minified if it is:
- being used in a node project because node has direct access to `node_modules`. Therefore minification has no advantages.
- being used as a module because projects that use a bundler often do minification themselves before creating a production build and importing a minified library can negatively affect tree shaing and code splitting.

Minification should be used if it is:
- being used in a script tag or delivered by a cdn like `<script src="https://unpkg.com/ical.js/dist/ical.es5.cjs"></script>` because in this case sending minified data over the network is more efficient since minification reduces the library size.

There are multiple ways to solve this (I'd prefer the first one):
- change `exports` section of `package.json` to differentiate how the library is imported like other librarys are doing
  - d3.js:
    ```json
      "module": "src/index.js",
      "main": "src/index.js",
      "jsdelivr": "dist/d3.min.js",
      "unpkg": "dist/d3.min.js",
      "exports": {
        "umd": "./dist/d3.min.js",
        "default": "./src/index.js"
      },
    ```
  - chart.js minifies their umd build, not the other ones
    ```json
        "jsdelivr": "./dist/chart.umd.js",
        "unpkg": "./dist/chart.umd.js",
        "main": "./dist/chart.cjs",
        "module": "./dist/chart.js",
        "exports": {
            ".": {
                "types": "./dist/types.d.ts",
                "import": "./dist/chart.js",
                "require": "./dist/chart.cjs"
            },
            "./auto": {
                "types": "./auto/auto.d.ts",
                "import": "./auto/auto.js",
                "require": "./auto/auto.cjs"
            },
            "./helpers": {
                "types": "./helpers/helpers.d.ts",
                "import": "./helpers/helpers.js",
                "require": "./helpers/helpers.cjs"
            }
        },
    ```

- provide sourcemaps to map the minified code back to the original code for development

I can create a PR if you want me to help out. It would be a minimal change I believe, it just needs some testing.

**Comment by jannikac** [comment]
Tested a bit more and figured out that by changing the `package.json`s `exports` key, VSCode `Go to definition` shows the correct, unminified code.

```diff
   "exports": {
-    "import": "./dist/ical.min.js",
-    "require": "./dist/ical.es5.min.cjs"
+    "import": "./dist/ical.js",
+    "require": "./dist/ical.es5.cjs"
   },
```
without the change:

![grafik](https://github.com/kewisch/ical.js/assets/21014142/086e155c-9aa1-4ea4-a2a7-dcaeffa4b0fc)

with the change:

![grafik](https://github.com/kewisch/ical.js/assets/21014142/f66edd24-23e6-4569-8dc6-f6ffec8d882b)

On a different node: maybe you could update the documentation that documents usage via a script tag. Because usually if you import a library in a script tag it should be minified since the library code is sent over the network. In the README.md you write that you can import it as a module with `https://unpkg.com/ical.js` or transpiled es5 `https://unpkg.com/ical.js/dist/ical.es5.cjs`. Both of those examples are unminified which they shouldn't be if they are being used in a script tag context. You have published minified packages on unpkg (`https://unpkg.com/ical.js@2.0.1/dist/ical.min.js`) but they are documented nowhere.

If you want, I can open a PR with these changes.

**Comment by kewisch** [comment]
Thank you for investigating! I've done some reading on this as well and I agree to change package.json to point to the unminified builds. Documenting all the CDN URLs as part of the readme makes sense as well, so those using via browser can use the minified URLs. A PR would be much appreciated, you've done such a great job on the last one!

**Comment by jannikac** [comment]
Created  a PR in #713, feel free to review.
