### ISSUE TITLE
`rollup-plugin-terser` reappeared in `package.json`

### ISSUE THREAD

**Issue by dilyanpalauzov** [kewisch/ical.js#706]
https://github.com/kewisch/ical.js/pull/693 has replaced in package.json "rollup-plugin-terser" with "@rollup/plugin-terser".  Later on, https://github.com/kewisch/ical.js/pull/662 added to package.json again "rollup-plugin-terser". Why?

**Comment by kewisch** [comment]
Ah I probably messed up the merge conflict while rebasing, apologies. I'll revert once I'm back at my laptop.
